services:
  - type: web
    name: validador-dispensa
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_PDF_SIZE_MB
        value: "50"
      - key: POWER_AUTOMATE_PROCESSO_URL
        sync: false
